"""add inscription_date to parents

Revision ID: 22f8d7aee03b
Revises: 
Create Date: 2025-04-21 22:45:14.922123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f8d7aee03b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('inscription_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('course', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('prefered_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'prefered_time')
    op.drop_column('students', 'course')
    op.drop_column('parents', 'inscription_date')
    # ### end Alembic commands ###
