"""change some attribute uniqueness

Revision ID: d01136d0e97a
Revises: df682e7c92de
Create Date: 2025-04-21 23:01:51.299805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01136d0e97a'
down_revision: Union[str, None] = 'df682e7c92de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parents_name', table_name='parents')
    op.create_index(op.f('ix_parents_name'), 'parents', ['name'], unique=True)
    op.drop_index('ix_students_name', table_name='students')
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.create_index('ix_students_name', 'students', ['name'], unique=False)
    op.drop_index(op.f('ix_parents_name'), table_name='parents')
    op.create_index('ix_parents_name', 'parents', ['name'], unique=False)
    # ### end Alembic commands ###
