"""change inscription_date to timestamp

Revision ID: df682e7c92de
Revises: 22f8d7aee03b
Create Date: 2025-04-21 22:51:36.557460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df682e7c92de'
down_revision: Union[str, None] = '22f8d7aee03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'inscription_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'inscription_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
